global:
  application_name: ReactStarter # Change this to your eb application's name
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on
    64bit Amazon Linux/2.14.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: git
  workspace_type: Application
